/**
 * Shared mood domain types for the Internet Mood Map app.
 *
 * These types are the single source of truth for the shape of mood data
 * across the API route, the dashboard UI, and any future data sources or
 * database models. Importing from here (instead of from the mock data file)
 * keeps the domain model independent of any specific data source.
 */

export type Mood =
  | "happy"
  | "angry"
  | "sad"
  | "stressed"
  | "excited"
  | "confused"
  | "fearful"
  | "hopeful"
  | "chaotic";

export type ActivityLevel = "low" | "medium" | "high";

export type RegionMood = {
  id: string;
  country: string;
  city: string;
  lat: number;
  lng: number;
  mood: Mood;
  moodScore: number;
  activityLevel: ActivityLevel;
  trendingTopics: string[];
  explanation: string;
  /**
   * Optional NLP-derived signal metadata. Populated by the data-source
   * orchestrator when emotion scoring is available; absent on raw mock
   * literals so the dataset stays readable.
   */
  confidence?: number;
  matchedKeywords?: string[];
  signalCount?: number;
};

export type MoodHistoryPoint = {
  time: string;
  happy: number;
  stressed: number;
  excited: number;
  hopeful: number;
  chaotic: number;
};

export type MoodSummary = {
  regionsSampled: number;
  globalMood: Mood;
  averageMoodScore: number;
  highActivityZones: number;
};

/**
 * High-level stats about the data sources that contributed to a single
 * /api/mood response. Optional in the API payload so older clients are
 * unaffected.
 */
export type SourceSummary = {
  sourceCount: number;
  signalCount: number;
  matchedSignalCount: number;
  unmatchedSignalCount: number;
};

/**
 * Modes used to describe how the data was sourced. This is informational
 * today (the MVP always uses the live-simulation path) but is wired through
 * so later phases can add hybrid/real data sources without changing the
 * response shape.
 */
export type MoodDataMode =
  | "mock"
  | "live-simulation"
  | "hybrid"
  | "real";

export type MoodApiResponse = {
  status: string;
  mode: MoodDataMode;
  generatedAt: string;
  summary: MoodSummary;
  regions: RegionMood[];
  history: MoodHistoryPoint[];
  /**
   * Non-fatal warnings produced while building the response (for example,
   * "real data source unavailable, falling back to mock"). Omitted when
   * everything went cleanly so existing clients see no shape change.
   */
  warnings?: string[];
  /**
   * Stats about the data sources that contributed to this response.
   * Present only when real / hybrid modes actually fetched signals.
   */
  sourceSummary?: SourceSummary;
  /**
   * Where the `history` array came from:
   *   "database" - reconstructed from MoodSnapshot rows
   *   "mock"     - bundled mock history / mock + drift
   * Omitted on responses produced before this metadata existed.
   */
  historySource?: "mock" | "database";
  /**
   * Which provider produced the `explanation` text on each region:
   *   "rule-based" - bundled rule-based text (default, deterministic)
   *   "openai"     - generated by OpenAI for every region in the response
   *   "gemini"     - generated by Google Gemini for every region
   *   "mixed"      - AI generated some, rule-based filled the rest
   */
  explanationSource?: "rule-based" | "openai" | "gemini" | "mixed";
};
